all: traceanal simpleProgram

traceanal: traceanal.cpp
	g++ traceanal.cpp -o traceanal

simpleProgram: simpleProgram.cpp
	g++ simpleProgram.cpp -o simpleProgram

clean:
	rm -f traceanal
	rm -f simpleProgram